name: 'add-wip-label'
description: 'Add WIP label to PR that title begin with `WIP: `.'
author: 'y-temp4'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'dist/index.js'
