name: "add-wip-label"
on:
  pull_request:
    types: [edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
